on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{github.job}}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Hello, ${{github.job}}"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Hello, ${{github.job}}"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo "Hello, ${{github.job}}"
