name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to?"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "App version to deploy"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
